// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ybnvoriewslmuwgfpdtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlibnZvcmlld3NsbXV3Z2ZwZHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDUzMjQsImV4cCI6MjA2NjMyMTMyNH0.059SA-9UDE5dzH0WIIhJiV-s69HZNeppyfTP19VFtUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);